version: 2
jobs:
  build:
    docker:
      - image: {{{ image }}}
    environment:
      R_LIBS: ~/R/Library
    steps:
      - restore_cache:
          keys:
            - r-pkg-cache-{{ arch }}-{{ .Branch }}
            - r-pkg-cache-{{ arch }}-
      - checkout
      - run:
          name: Install package dependencies
          command: |
            mkdir -p ~/R/Library
            R -e 'install.packages("remotes")'
            R -e 'remotes::install_deps(dependencies = TRUE)'
      - run:
          name: Build package
          command: R CMD build .
      - run:
          name: Check package
          command: R CMD check --as-cran --no-manual *tar.gz
      - store_artifacts:
          path: {{{ package }}}.Rcheck/
      - save_cache:
          key: r-pkg-cache-{{ arch }}-{{ .Branch }}
          paths:
            - "~/R/Library"
